---
- name: create flavor
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "{{ username | default(None) }}"
    OS_PASSWORD: "{{ pass | default(None) }}"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_DNS_NAMESERVER1: "8.8.8.8"
    OS_PROJECT_NAME: "{{ project | default(None) }}"

#vars flavor
    NAME_FLAVOR: "{{ flavor| default(None) }}"
    DISQUE_FLAVOR: "{{ Go | default(None) }}"

  tasks:

    - name: create a flavor
      os_nova_flavor:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT_NAME }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ NAME_FLAVOR }}"
       disk: "{{ DISQUE_FLAVOR }}"


