---
- name: create instance
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "{{ user | default(None) }}"
    OS_PASSWORD: "{{ pass | default(None) }}"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_DNS_NAMESERVER1: "8.8.8.8"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"

#vars instance
    NAME_INSTANCE: "{{ name | default(None) }}"
    NAME_IMAGE: "cirros-0.5.1-x86_64-disk"
    NAME_INT_NETWORK: "{{ int_network| default(None) }}"
    SECURITY_GROUP: "{{ sc_grp | default(None) }}"
    KEY_NAME: "{{ key | default(None) }}"
    NAME_FLAVOR: "m1.tiny"
  tasks:

    - name: create a new instance
      os_server:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ NAME_INSTANCE }}"
       image: "{{ NAME_IMAGE }}"
       key_name: "{{ KEY_NAME }}"
       flavor: "{{ NAME_FLAVOR }}"
       network: "{{ NAME_INT_NETWORK }}"
       security_groups: "{{ SECURITY_GROUP }}"
       auto_ip: yes
       region_name: RegionOne


