---
- name: create ext_net
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_DNS_NAMESERVER1: "8.8.8.8"

#vars externe network
    NAME_EXT_NETWORK: "{{ ext_network | default(None) }}"
#vars externe subnet
    NAME_EXT_SUBNET: "{{ ext_subnet | default(None) }}"
    CIDR_SUBNET: "{{ adresse_subnet | default(None) }}"
    DNS_NAMESERVERS: "8.8.8.8"
    ALLOCATION_POOL_START: "{{ pool_start | default(None) }}"
    ALLOCATION_POOL_END: "{{ pool_end | default(None) }}"


  tasks:

    - name : create an externe network
      os_network:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_EXT_NETWORK }}"
        external: true
        shared: yes

    - name: create an externe subnet
      os_subnet:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        network_name: "{{ NAME_EXT_NETWORK }}"
        name: "{{ NAME_EXT_SUBNET }}"
        cidr: "{{ CIDR_SUBNET }}"
        enable_dhcp: yes
        allocation_pool_start: "{{ ALLOCATION_POOL_START }}"
        allocation_pool_end: "{{ ALLOCATION_POOL_END }}"
        dns_nameservers: "{{ DNS_NAMESERVERS }}"
