---
- name: create int_net
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"

    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
    DNS_NAMESERVER: "8.8.8.8"
#vars interne network
    NAME_INT_NETWORK: "{{ int_network | default(None) }}"
#vars interne subnet
    NAME_INT_SUBNET: "{{ int_subnet | default(None) }}"
    CIDR_INT_SUBNET: "{{ cidr | default(None) }}"

  tasks:
    
    - name : create an interne  network
      os_network:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_INT_NETWORK }}"
        project: "{{ OS_PROJECT }}"    
    - name: create an interne subnet
      os_subnet:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        network_name: "{{ NAME_INT_NETWORK }}"
        name: "{{ NAME_INT_SUBNET }}"
        cidr: "{{ CIDR_INT_SUBNET }}"
        dns_nameservers: "{{ DNS_NAMESERVERS }}"
        project: "{{ OS_PROJECT }}"
