---
- name: create project
  hosts: all
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"

#vars project
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}" 
    OS_DNS_NAMESERVER1: "8.8.8.8"
  tasks:
    - debug: var=ansible_host
    - name: Create a project
      os_project:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        region_name: RegionOne
        domain_id: default
        name: "{{ OS_PROJECT }}"
    - name: Attach admin to project
      os_user_role:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        user: admin
        role: admin
        project: "{{ OS_PROJECT }}"
...
