
---
- name: définir les quotas
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_DNS_NAMESERVER1: "8.8.8.8"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
#vars quota
    INSTANCES_PROJECT: "{{ instances | default(None) }}"
    CORES_PROJECT: "{{ cores | default(None) }}"
    RAM_PROJECT: "{{ ram | default(None) }}"
    VOLUMES_PROJECT: "{{ volumes | default(None) }}"
    SNAPSHOTS_PROJECT: "{{ snapshot | default(None) }}"
    NETWORK_PROJECT: "{{ network | default(None) }}"
    GIGABYTES_PROJECT: "{{ storage | default(None) }}"


  tasks:
    - name: set a project quotas
      os_quota:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT_NAME }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ OS_PROJECT }}"
       instances: "{{ INSTANCES_PROJECT }}"
       cores: "{{ CORES_PROJECT }}"
       ram: "{{ RAM_PROJECT }}"
       volumes: "{{ VOLUMES_PROJECT }}"
       snapshots: "{{ SNAPSHOTS_PROJECT }}"
       network: "{{ NETWORK_PROJECT }}"
       gigabytes: "{{ GIGABYTES_PROJECT }}"
