---
- name: create router
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_PROJECT_NAME: "admin"
    OS_DNS_NAMESERVER1: "8.8.8.8"
    OS_PROJECT: "{{ project | default(None) }}"
#vars router
    NAME_ROUTER: "{{ router | default(None) }}"
    NAME_EXT_NETWORK: "{{ ext_network | default(None) }}"
    NAME_EXT_SUBNET: "{{ ext_subnet | default(None) }}"
    NAME_INT_SUBNET: "{{ int_subnet | default(None) }}"
    NAME_INT_NETWORK: "{{ int_network | default(None) }}"
  tasks:

    - name: create a router
      os_router:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"

          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ NAME_ROUTER }}"
        network: "{{ NAME_EXT_NETWORK }}"
        external_fixed_ips:
          - subnet: "{{ NAME_EXT_SUBNET }}"
        interfaces:
          - "{{ NAME_INT_SUBNET }}"
        enable_snat: yes
        project: "{{ OS_PROJECT }}"

